### ISSUE TITLE
Request: ability to intercept touch event

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#37] opened 2018-06-24 18:38 UTC
Hi,

I have been given a requirement where a previously completed question is edited, that the user see a message first to confirm they wish to edit the field.

Currently, the only listener is after they have chosen a value, I show a dialog asking them to confirm the change and then manually set the value to the old value if they say cancel.

Edit: If i set the value back because they chose cancel, won't the listener fire again putting me in a loop?

**Comment by TheJuki** [comment] 2018-06-25 14:47
I'll work on the first part of your issue. As far as updating the value of the form element within valueObserver or onValueChanged, you would need to check if the new value is different before setting it again. You can do this by setting the current value somewhere else and checking against that.

**Comment by dhaksddj** [comment] 2018-06-27 09:29
Can I help with this in anyway?

**Comment by dhaksddj** [comment] 2018-06-27 13:22
I've tried to make this work without the change but its not easy.

Since the only listener is after they have changed the value, I need to reset it back (if they decide to abandon the change, I show a dialog to confirm). However, this is not trivial to do and I'm not convinced setting the value back won't fire the listener again.

Thoughts?

**Comment by TheJuki** [comment] 2018-06-27 13:43
Do you need this for all elements or just the ones that display a dialog when tapped? The ones that display a dialog anyway would be easier to make to make this change since the whole element is controlled by one on click listener. So, instead of intercepting the show dialog event somehow, I could just add an optional Confirm dialog there with the ability to supply your own title and message per element. The OK button would show the dialog and the Cancel button would just close the Confirm dialog. Would that work for you?

**Comment by dhaksddj** [comment] 2018-06-27 13:48
Yes, they are dialogs only at this point.

That might work but under what circumstances would it know to show the optional Confirm dialog? It would have to be when the element already has a value(?)

**Comment by TheJuki** [comment] 2018-06-27 14:00
It's up to you. I'll add a new Boolean variable to the base element class: confirmEdit. If it makes sense to also check if the field is not null as well I can check for that too before showing the confirm dialog.

**Comment by dhaksddj** [comment] 2018-06-27 14:01
I'm happy to try that out and see if it meets my requirements. Any idea how long it might take?

**Comment by TheJuki** [comment] 2018-06-27 14:03
1-2 hours. I'll just add it to dialog elements for now. So, the if should be:

`if(value != null && confirmEdit)`

**Comment by dhaksddj** [comment] 2018-06-27 14:04
that would be great! Thank you.

**Comment by TheJuki** [comment] 2018-06-27 16:38
I just released [4.4.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new confirm dialog works for you. Just set confirmEdit to true.

**Comment by dhaksddj** [comment] 2018-06-27 16:39
Thanks! Will do.

**Comment by TheJuki** [comment] 2022-04-18 03:36
I am closing this issue. If you have any issues feel free to reopen.

**Closed by TheJuki** 2022-04-18 03:36 UTC
Labels: enhancement
