### ISSUE TITLE
Listener called for non-modified text fields

### ISSUE THREAD

**Issue by acedward** [TheJuki/KFormMaster#6] opened 2018-04-06 00:24 UTC
Thanks for the great library!

I hope you can help me with an issue, the listener is called on an element that is not modified.
I've checked the implementation and I cannot figure why the listener is called on the non-modified field.

Thanks in advance for any tips or advice

This is my setup:
```

private enum class PTag {
            P_NAME,
           // ... other tags
            DOC_NAME,
        }

formBuilder = form(this.context!!, recyclerView, listener) {

                header { title = "Patient Info" }
                text(PTag.P_NAME.ordinal) {
                    title = "Name"
                    value = prefs!!.getString(PTag.P_NAME.name, "")
                }
               header { title = "Doctor Info" }
                text(PTag.DOC_NAME.ordinal) {
                    title = "Doctor Name"
                    value = prefs!!.getString(PTag.DOC_NAME.name, "")
                }
```
![error](https://user-images.githubusercontent.com/3951895/38398002-fdf08688-3916-11e8-8123-51545fa1ca5d.gif)

**Comment by TheJuki** [comment] 2018-04-06 01:34
Based on my current example app in this rep I cannot reproduce this with the "Form with Listener" activity. Can you provide your entire form block? 

I believe that are using the listener as a way to reduce code. 

However, you can try to adding a valueObserver to each element. 

Let me know if the same issue occurs.

Also, you may want to use `lateinit var prefs: SharedPreferences` so that you do not need use `prefs!!` after it is initialized.

```
 text(PTag.P_NAME.ordinal) {
    title = "Name"
    value = prefs!!.getString(PTag.P_NAME.name, "")
    valueObservers.add({ newValue, element ->
        val editor = prefs!!.edit()
        editor.putString(Tag.P_NAME.name, newValue)
        editor.apply()
    })
}
```

**Comment by TheJuki** [comment] 2018-05-17 21:09
This has been "fixed". CacheForm is true by default now to fix the RecyclerView weirdness. I am closing this issue. However, feel free to reopen.

**Closed by TheJuki** 2018-05-17 21:09 UTC
Labels: bug
